<?xml version="1.0"?>
<package format="3">
  <name>curt_mini_teleop</name>
  <version>0.1.0</version>
  <description>Joystick teleoperation for Curt Mini</description>
  <maintainer email="tobias.rainer.schaefle@ipa.fraunhofer.de">ipa-trs</maintainer>
  <license>TODO: License declaration</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>joy_linux</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
